recipient: backup@bitcoin-central.net
ftp_servers:
  server1:
    host: ftp.domain.tld
    username: user
    password: pass
  server2:
    host: ftp2.domain.tld
    username: user
    password: pass