development:
  adapter: mysql2
  encoding: utf8
  database: bitcoin-bank_development
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: bitcoin-bank_test
  username: root
  password:

# production:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: bitcoin-bank_production
#   pool: 5
#   host: localhost
#   username: root
#   password: qazwsx
#   socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  database: rails
  username: rails
  password: P9iOywQ9Ko
  host: localhost